- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install base packages
  apt:
    name:
      - batctl
      - iw
      - wireless-tools
      - curl
    state: present
