- name: Install Avahi and utils
  apt:
    name:
      - avahi-daemon
      - avahi-utils
    state: present

- name: Ensure avahi-daemon is enabled and started
  systemd:
    name: avahi-daemon
    enabled: true
    state: started

- name: Check Avahi services on the node
  command: avahi-browse -a -t
  register: avahi_services
  changed_when: false
  tags: [debug]
