- name: Bootstrap mesh nodes
  hosts: mesh_nodes
  become: true

  roles:
    - base
    - mesh
    - discovery
    - {
        role: services,
        when: "'service_nodes' in group_names",
        tags: ["services"],
      }
